app.controller('etteremnyitvatartasCtrl',function($scope,$rootScope,dbfactory){
    $rootScope.sidebar=false;
    $scope.nyitas=[];
    $scope.modID=0;
    if($rootScope.logJog=="etterem"){ 
        dbfactory.etteremid($rootScope.EtteremEmail).then(function(r){
             if(r.data.length>0)
             {
                 $rootScope.selectedetteremID=r.data[0].ID;
                 dbfactory.open($rootScope.selectedetteremID).then(function(res){
                     if(res.data.length>0)
                     {
                         $scope.nyitas=res.data;
                     }
                 });
             }   
         });
     }
     else
     {
         dbfactory.open($rootScope.selectedetteremID).then(function(res){
             if(res.data.length>0)
             {
                 $scope.nyitas=res.data;
             }
         });
     }
     $scope.egyvalaszt=function(id)
     {
        $scope.modID=id;
     }
     $scope.select=function(id)
     {
         $scope.ujnyitas=$scope.nyitas[id].Nyitas;
         $scope.ujzaras=$scope.nyitas[id].Zaras;
     }
     $scope.update=function()
     {
        dbfactory.openupdate($scope.modID,$scope.ujnyitas,$scope.ujzaras).then(function(res){
            dbfactory.open($rootScope.selectedetteremID).then(function(res){
                if(res.data.length>0)
                {
                    $scope.nyitas=res.data;
                }
            });
        })
     }
})