app.controller('etteremetlapCtrl',function($scope,$rootScope,$location,dbfactory,Notify){

    $rootScope.felvesz2=1;
        $scope.etteremad=0;
        $scope.ujnevetel=null;
        $scope.ujar=null;
        $scope.ujleirasetel=null;
        $rootScope.sidebar=false;
        $scope.etlap=[];
        $scope.torolegyid=0;
       if($rootScope.logJog=="etterem"){ 
           dbfactory.etteremid($rootScope.EtteremEmail).then(function(r){
                if(r.data.length>0)
                {
                    $rootScope.selectedetteremID=r.data[0].ID;
                    dbfactory.adminfoodselect($rootScope.selectedetteremID).then(function(res){
                        if(res.data.length>0)
                        {
                            $scope.etlap=res.data;
                        }
                    });
                }   
            });
        }
        else
        {
            dbfactory.adminfoodselect($rootScope.selectedetteremID).then(function(res){
                if(res.data.length>0)
                {
                    $scope.etlap=res.data;
                }
            });
        }
        $scope.visszavaltas=function(){
            $location.path('#!/admin');
        }
        $scope.selectRowEtlap=function($id)
        {
            $scope.ujID=$scope.etlap[$id].ID;
            $scope.ujnevetel=$scope.etlap[$id].Nev;
            $scope.ujar=$scope.etlap[$id].Ar;
            $scope.ujleirasetel=$scope.etlap[$id].Leiras;
            $rootScope.felvesz2=0;
        }
        $scope.unselectRowEtlap=function(){
            $rootScope.felvesz2=1;
            $scope.ujnevetel=null;
            $scope.ujar=null;
            $scope.ujleirasetel=null;
        }
            
        $scope.insertEtlap=function()
        {
            if($scope.ujnevetel==null|| $scope.ujar==null)
            {
                
                Notify.addMessage('A kellő adatok nincsenek kitöltve ', "danger");
            }
            else
            {
                dbfactory.adminfoodinsert($rootScope.selectedetteremID,$scope.ujnevetel,$scope.ujar, $scope.ujleirasetel).then(function(res){
                    dbfactory.adminfoodselect($rootScope.selectedetteremID).then(function(res){
                        if(res.data.length>0)
                        {
                            $scope.etlap=res.data;
                        }
                    });
                })
                $scope.unselectRowEtlap();
            }
           
        }
        $scope.egyvalaszt=function(id)
        {
            $scope.torolegyid=$scope.etlap[id].ID;
        }
        $scope.deleteRecord=function()
        {
            dbfactory.adminfooddelete($scope.torolegyid).then(function(res){
                dbfactory.adminfoodselect($rootScope.selectedetteremID).then(function(res){
                    if(res.data.length>0)
                    {
                        $scope.etlap=res.data;
                    }
                    $scope.unselectRowEtlap();
                });
            })
        }
        $scope.updateEtlap=function()
        {
            if($scope.ujnevetel==null|| $scope.ujar==null)
            {
                
                Notify.addMessage('A kellő adatok nincsenek kitöltve ', "danger");
            }
            else
            {
                dbfactory.adminfoodupdate($scope.ujID,$rootScope.selectedetteremID,$scope.ujnevetel,$scope.ujar,$scope.ujleirasetel).then(function(res){
                    dbfactory.adminfoodselect($rootScope.selectedetteremID).then(function(res){
                        if(res.data.length>0)
                        {
                            $scope.etlap=res.data;
                        }
                        $scope.unselectRowEtlap();
                    });
                })
            }
        }
})