app.controller('etteremkepekCtrl',function($scope,$rootScope,dbfactory){
    $rootScope.sidebar=false;
    $scope.kepek=[];
    $scope.modID=0;
    if($rootScope.logJog=="etterem"){ 
        dbfactory.etteremid($rootScope.EtteremEmail).then(function(r){
             if(r.data.length>0)
             {
                 $rootScope.selectedetteremID=r.data[0].ID;
                 dbfactory.open($rootScope.selectedetteremID).then(function(res){
                     if(res.data.length>0)
                     {
                         $scope.kepek=res.data;
                     }
                 });
             }   
         });
     }
     else
     {
        
         dbfactory.open($rootScope.selectedetteremID).then(function(res){
             if(res.data.length>0)
             {
                 $scope.kepek=res.data;
             }
         });
     }
     $scope.select=function(id)
     {
         $scope.modID=id;
     }
})